POST http://localhost:8080/jwt
Content-Type: application/json

{
  "market": "KRW-XRP",
  "side": "bid",
  "volume": 50,
  "price": 100,
  "ord_type": "limit"
}

###
POST http://localhost:8080/order
Content-Type: application/json

{
  "side": "bid",
  "user_id" : 1,
  "ticker_symbol" : "KRW-XRP",
  "price" : 100.0,
  "quantity" : 50.0
}

###
POST http://localhost:8080/order
Content-Type: application/json

{
  "side": "ask",
  "user_id" : 1,
  "ticker_symbol" : "KRW-XRP",
  "price" : 1000.0,
  "quantity" : 26.0
}